package Interface;

import BaseDados.JavaConexao;
import CRUD.ContactoUtil;
import CRUD.DepartamentoUtil;
import CRUD.FuncaoUtil;
import CRUD.FuncionarioUtil;
import Classes.Contacto;
import Classes.Departamento;
import Classes.Funcao;
import Classes.Funcionarios;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author EGV
 */
public class FuncionarioCadastro extends javax.swing.JFrame {

    JavaConexao acbase = new JavaConexao();
    FuncionarioUtil futil = new FuncionarioUtil(); 
    Funcionarios func = new Funcionarios();
    Contacto conta = new Contacto();
    ContactoUtil contut = new ContactoUtil();
    Departamento dep = new Departamento();
    DepartamentoUtil deputil = new DepartamentoUtil();
    Funcao fuc = new Funcao();
    FuncaoUtil fucut = new FuncaoUtil();
////    SimpleDateFormat FormatoData; 
    
    TelaAdmin ta =new TelaAdmin();
    
    
    public FuncionarioCadastro() {
        initComponents();
        //acbase.Conexao();
        //setExtendedState(JFrame.MAXIMIZED_BOTH); abrindo maximizado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGrupoSexo = new javax.swing.ButtonGroup();
        DesktopFunc = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTnomeFuncio = new javax.swing.JTextField();
        jTApelido = new javax.swing.JTextField();
        jTBi = new javax.swing.JTextField();
        jTnuitFunc = new javax.swing.JTextField();
        jTtelefoneFunc = new javax.swing.JTextField();
        jTemailFunc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCcateg = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTprovFunc = new javax.swing.JTextField();
        jTlocalidadFunc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jCDepartamento = new javax.swing.JComboBox<>();
        pesquisarFun = new javax.swing.JButton();
        FunCadd = new javax.swing.JButton();
        FunCgravar = new javax.swing.JButton();
        FunCVoltar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTsenha = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTcFuncio = new javax.swing.JTextField();
        jTdata = new javax.swing.JTextField();
        FunCreport1 = new javax.swing.JButton();
        jTUser = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jBAtualizar = new javax.swing.JButton();
        jComboFuncao = new javax.swing.JComboBox<>();
        jComboNivel = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jRadioMasculino = new javax.swing.JRadioButton();
        jRadioFemenino = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulário de Cadastro");
        setSize(new java.awt.Dimension(1000, 1000));

        DesktopFunc.setBackground(new java.awt.Color(255, 255, 255));
        DesktopFunc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DesktopFunc.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(570, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 36)); // NOI18N
        jLabel1.setText("Formulário de Cadastro");

        jLabel2.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel2.setText("*Nome");

        jLabel3.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel3.setText("*Apelido");

        jLabel4.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel4.setText("*Nr. de Identificação ");

        jLabel5.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel5.setText("*Telefone");

        jLabel6.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel6.setText("*Nuit");

        jLabel7.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel7.setText("*Departamento");

        jLabel8.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel8.setText("E-mail");

        jLabel9.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel9.setText("Perfil");

        jTnomeFuncio.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jTnomeFuncio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTnomeFuncio.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTnomeFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeFuncioActionPerformed(evt);
            }
        });

        jTApelido.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N

        jTBi.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jTBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBiActionPerformed(evt);
            }
        });

        jTnuitFunc.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N

        jTtelefoneFunc.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N

        jTemailFunc.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel10.setText("Sexo");

        jLabel11.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel11.setText("*Nível Académico");

        jCcateg.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jCcateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionário", "Administrador" }));
        jCcateg.setToolTipText("");
        jCcateg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCcateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcategActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel12.setText("*Data de Nascimento");

        jLabel14.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel14.setText("*Distrito da Morada");

        jLabel15.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel15.setText("*Bairro");

        jTprovFunc.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N

        jTlocalidadFunc.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel16.setText("*Função");

        jCDepartamento.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jCDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione. . .", "Ciências de  Administração e  Gestão", "Ciências de Educação", "Engenharia Informática e Tecnologica", "Teologia" }));
        jCDepartamento.setToolTipText("Ciências de  Administração e  Gestão,  Ciências de Educação,  Engenharia Informática e Tecnologica,  Teologia");
        jCDepartamento.setBorder(null);

        pesquisarFun.setBackground(new java.awt.Color(255, 255, 255));
        pesquisarFun.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        pesquisarFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/worker.png"))); // NOI18N
        pesquisarFun.setToolTipText("Relatório");
        pesquisarFun.setBorder(null);
        pesquisarFun.setBorderPainted(false);
        pesquisarFun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesquisarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarFunActionPerformed(evt);
            }
        });

        FunCadd.setBackground(new java.awt.Color(255, 255, 255));
        FunCadd.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        FunCadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        FunCadd.setToolTipText("Cadastrar outro");
        FunCadd.setBorder(null);
        FunCadd.setBorderPainted(false);
        FunCadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FunCadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunCaddActionPerformed(evt);
            }
        });

        FunCgravar.setBackground(new java.awt.Color(255, 255, 255));
        FunCgravar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        FunCgravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Save.png"))); // NOI18N
        FunCgravar.setToolTipText("Gravar Cadastro");
        FunCgravar.setBorder(null);
        FunCgravar.setBorderPainted(false);
        FunCgravar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FunCgravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunCgravarActionPerformed(evt);
            }
        });

        FunCVoltar.setBackground(new java.awt.Color(255, 255, 255));
        FunCVoltar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        FunCVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Backk.png"))); // NOI18N
        FunCVoltar.setToolTipText("Voltar");
        FunCVoltar.setBorder(null);
        FunCVoltar.setBorderPainted(false);
        FunCVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FunCVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunCVoltarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel18.setText("Senha");

        jTsenha.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel19.setText("Cód do Funcionário");
        jLabel19.setToolTipText("Código do Funcionário");

        jTcFuncio.setEnabled(false);
        jTcFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcFuncioActionPerformed(evt);
            }
        });

        jTdata.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jTdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdataActionPerformed(evt);
            }
        });

        FunCreport1.setBackground(new java.awt.Color(255, 255, 255));
        FunCreport1.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        FunCreport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/clipboard.png"))); // NOI18N
        FunCreport1.setToolTipText("Relatório");
        FunCreport1.setBorder(null);
        FunCreport1.setBorderPainted(false);
        FunCreport1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FunCreport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunCreport1ActionPerformed(evt);
            }
        });

        jTUser.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel20.setText("Usuário");

        jBAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        jBAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/update.png"))); // NOI18N
        jBAtualizar.setBorder(null);
        jBAtualizar.setBorderPainted(false);

        jComboFuncao.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jComboFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhuma. . .", "Corpo Técnico Administrativo", "Docente", "Pessoal de Apoio", "Reitor" }));
        jComboFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboFuncaoActionPerformed(evt);
            }
        });

        jComboNivel.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jComboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione. . .", "Básico", "Médio", "Bacharel", "Liccenciado", "Mestre", "Doutor", "PHP" }));

        jLabel13.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel13.setText("Campo brigatório");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel17.setText("*");

        BGrupoSexo.add(jRadioMasculino);
        jRadioMasculino.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jRadioMasculino.setText("Masculino");
        jRadioMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMasculinoActionPerformed(evt);
            }
        });

        BGrupoSexo.add(jRadioFemenino);
        jRadioFemenino.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jRadioFemenino.setText("Femenino");

        javax.swing.GroupLayout DesktopFuncLayout = new javax.swing.GroupLayout(DesktopFunc);
        DesktopFunc.setLayout(DesktopFuncLayout);
        DesktopFuncLayout.setHorizontalGroup(
            DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
            .addGroup(DesktopFuncLayout.createSequentialGroup()
                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesktopFuncLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DesktopFuncLayout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DesktopFuncLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTBi)
                            .addComponent(jTnuitFunc)
                            .addComponent(jTApelido)
                            .addComponent(jTnomeFuncio)
                            .addComponent(jTdata)
                            .addComponent(jTprovFunc)
                            .addComponent(jTlocalidadFunc)
                            .addComponent(jTtelefoneFunc)
                            .addComponent(jTemailFunc)
                            .addComponent(jComboFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(DesktopFuncLayout.createSequentialGroup()
                                .addComponent(jRadioMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioFemenino, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesquisarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(DesktopFuncLayout.createSequentialGroup()
                                    .addComponent(FunCadd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(FunCVoltar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBAtualizar)
                                    .addGap(10, 10, 10)
                                    .addComponent(FunCgravar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FunCreport1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(DesktopFuncLayout.createSequentialGroup()
                                    .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTsenha)
                                        .addComponent(jTUser)
                                        .addComponent(jCcateg, 0, 246, Short.MAX_VALUE)
                                        .addComponent(jCDepartamento, 0, 1, Short.MAX_VALUE)
                                        .addComponent(jTcFuncio)
                                        .addComponent(jComboNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(18, 18, 18))
        );
        DesktopFuncLayout.setVerticalGroup(
            DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopFuncLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesktopFuncLayout.createSequentialGroup()
                        .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DesktopFuncLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DesktopFuncLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jTApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTnomeFuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pesquisarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTBi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioMasculino)
                                    .addComponent(jRadioFemenino))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTnuitFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTdata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jComboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTtelefoneFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(DesktopFuncLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTcFuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(11, 11, 11)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jCcateg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DesktopFuncLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTemailFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(DesktopFuncLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DesktopFuncLayout.createSequentialGroup()
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DesktopFuncLayout.createSequentialGroup()
                                        .addComponent(jTprovFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTlocalidadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(DesktopFuncLayout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FunCadd)
                                    .addComponent(FunCreport1))
                                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FunCgravar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FunCVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBAtualizar, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(DesktopFuncLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel10)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(DesktopFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        DesktopFuncLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel12, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jTApelido, jTBi, jTemailFunc, jTlocalidadFunc, jTnomeFuncio, jTnuitFunc, jTprovFunc, jTtelefoneFunc});

        DesktopFuncLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCcateg, jLabel11, jLabel7, jLabel9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1000, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCcategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcategActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCcategActionPerformed

    private void jTnomeFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeFuncioActionPerformed

    private void FunCVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunCVoltarActionPerformed
        // botao para voltar menu anterior
        dispose();
        ta.setVisible(true);
    }//GEN-LAST:event_FunCVoltarActionPerformed

    private void FunCgravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunCgravarActionPerformed
            
    try {   if(validarCampos()){
         
                if(preencherCadastro())
                 //gravar na BD
                    if(futil.Gravar(func)){
                       JOptionPane.showMessageDialog(null, "Cadastro bem sucedido");
                       limparCampos();
                       
                        FunCVoltar.setEnabled(true);
                        FunCadd.setEnabled(true);
                        FunCgravar.setEnabled(false);
                        pesquisarFun.setEnabled(true);
                 }else
                     JOptionPane.showMessageDialog(null, "Nao foi posssivel cadastrar funcionario");
         } 
            }catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Ërro de insersao"+ex);    
     }
         
    }//GEN-LAST:event_FunCgravarActionPerformed

    private void FunCaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunCaddActionPerformed
            limparCampos();
            activarCampos();
            FunCVoltar.setEnabled(true);
            FunCadd.setEnabled(false);
            FunCgravar.setEnabled(true);
            pesquisarFun.setEnabled(false);
          
       
    }//GEN-LAST:event_FunCaddActionPerformed

    private void pesquisarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarFunActionPerformed
         if (jTnomeFuncio.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Digite o nome para a pesquisa");
             jTnomeFuncio.requestFocus();
         }else{
             FuncionarioUtil fu = new FuncionarioUtil();
             try {
                 func = fu.pesquisar(jTnomeFuncio.getText());
             } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, "Erro" +ex);
             }
             if(func==null){
                 JOptionPane.showMessageDialog(null, "Registro nao enconntrado");
             }else{
                 jTnomeFuncio.setText(func.getNome()+"");
                 jTApelido.setText(func.getApelido());
                 jRadioMasculino.setText(func.getSexo());
                 jRadioFemenino.setText(func.getSexo());
                 jTBi.setText(func.getBi());
                 jTdata.setText(func.getDataNasc());
               //  jTnuitFunc.setText((func.getNuit()));
                 jTprovFunc.setText(func.getProvincia());
                 jTlocalidadFunc.setText(func.getDistrito());
                 jTsenha.setText(func.getSenha());
                 jTUser.setText(func.getUsuario());
                 jCcateg.setSelectedItem(func.getPerfil());
                 
             }
         }
           
            
        
    }//GEN-LAST:event_pesquisarFunActionPerformed

    private void jTcFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcFuncioActionPerformed

    private void jTdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdataActionPerformed

    private void jTBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBiActionPerformed

    private void FunCreport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunCreport1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FunCreport1ActionPerformed

    private void jComboFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboFuncaoActionPerformed

    private void jRadioMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioMasculinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGrupoSexo;
    public javax.swing.JPanel DesktopFunc;
    private javax.swing.JButton FunCVoltar;
    private javax.swing.JButton FunCadd;
    private javax.swing.JButton FunCgravar;
    private javax.swing.JButton FunCreport1;
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JComboBox<String> jCDepartamento;
    private javax.swing.JComboBox<String> jCcateg;
    private javax.swing.JComboBox<String> jComboFuncao;
    private javax.swing.JComboBox<String> jComboNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioFemenino;
    private javax.swing.JRadioButton jRadioMasculino;
    private javax.swing.JTextField jTApelido;
    private javax.swing.JTextField jTBi;
    private javax.swing.JTextField jTUser;
    private javax.swing.JTextField jTcFuncio;
    private javax.swing.JTextField jTdata;
    private javax.swing.JTextField jTemailFunc;
    private javax.swing.JTextField jTlocalidadFunc;
    private javax.swing.JTextField jTnomeFuncio;
    private javax.swing.JTextField jTnuitFunc;
    private javax.swing.JTextField jTprovFunc;
    private javax.swing.JTextField jTsenha;
    private javax.swing.JTextField jTtelefoneFunc;
    private javax.swing.JButton pesquisarFun;
    // End of variables declaration//GEN-END:variables

    public boolean preencherCadastro() throws Exception{
       func.setNome(jTnomeFuncio.getText()); 
       func.setApelido(jTApelido.getText());
       func.setBi(jTBi.getText());
       func.setSexo(jRadioMasculino.getText()); //Converter em string, uma vez que ele é um botao de opcoes.
       func.setSexo(jRadioFemenino.getText());
       func.setNuit(Integer.parseInt(jTnuitFunc.getText())); //Convertendo Int para leitura 
       func.setNivelacad(jComboNivel.getSelectedItem().toString());
       func.setDataNasc(jTdata.getText());     
       func.setProvincia(jTprovFunc.getText());
       func.setDistrito(jTlocalidadFunc.getText());
       func.setSenha(jTsenha.getText());
       func.setUsuario(jTUser.getText());
       dep.setNomeDep(jCDepartamento.getSelectedItem().toString());
       func.setPerfil(jCcateg.getSelectedItem().toString());
       fuc.setNomeFunc(jComboFuncao.getSelectedItem().toString());
       conta.setTelefone(Integer.parseInt(jTtelefoneFunc.getText()));
       conta.setEmail(jTemailFunc.getText());
       //invocacao dos metodos que manipulam a gravacao
       futil.Gravar(func);
       contut.gravarCont(conta);
       fucut.gravarFuncao(fuc);
       deputil.gravarDep(dep);
       return true;
    }
    private void limparCampos(){
        jTApelido.setText("");
        jTBi.setText("");
        jTemailFunc.setText("");
        jComboFuncao.setSelectedItem(0);
        jTlocalidadFunc.setText("");
        jTsenha.setText("");
        jComboNivel.setSelectedItem(0);
        jTnomeFuncio.setText("");
        jTnuitFunc.setText("");
        jTprovFunc.setText("");
        jTsenha.setText("");
        jComboNivel.setSelectedItem(0);
        jTtelefoneFunc.setText("");
        jCDepartamento.setSelectedItem("");
        jCcateg.setSelectedIndex(0);
        jCDepartamento.setSelectedIndex(0);
        jTUser.setText("");
    }
    private void desativarCampos(){
        jTApelido.setEnabled(false);
        jTBi.setEnabled(false);
        jTemailFunc.setEnabled(false);
        jComboFuncao.setEnabled(false);
        jTlocalidadFunc.setEnabled(false);
        jComboNivel.setEnabled(false);
        jTnomeFuncio.setEnabled(false);
        jTnuitFunc.setEnabled(false);
        jTprovFunc.setEnabled(false);
        jTtelefoneFunc.setEnabled(false);
        jTsenha.setEnabled(false);
        jRadioMasculino.setEnabled(false);
        jRadioFemenino.setEnabled(false);
        jCDepartamento.setEnabled(false);
        jCcateg.setEnabled(false);
        jTcFuncio.setEnabled(false);
        jTdata.setEnabled(false);
    }
    private void activarCampos(){
        jTUser.setEnabled(false);
        //jTPesq.setEditable(false);
        jTApelido.setEnabled(true);
        jTBi.setEnabled(true);
        jTemailFunc.setEnabled(true);
        jComboFuncao.setEnabled(true);
        jTlocalidadFunc.setEnabled(true);
        jComboNivel.setEnabled(true);
        jTnomeFuncio.setEnabled(true);
        jTnuitFunc.setEnabled(true);
        jTprovFunc.setEnabled(true);
        jTtelefoneFunc.setEnabled(true);
        jTsenha.setEnabled(true);
        jRadioMasculino.setEnabled(true);
        jRadioFemenino.setEnabled(true);
        jCDepartamento.setEnabled(true);
        jCcateg.setEnabled(true);
        jTcFuncio.setEnabled(true);
        jTdata.setEnabled(true);
    }
          
    private boolean validarCampos(){
    
    if(jTnomeFuncio.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Digite o Nome");
        jTnomeFuncio.requestFocus(); //Chama o cursor 
        return false;
    }
    else if(jTApelido.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Digite o Apelido");
       jTApelido.requestFocus();
       return false;
    }
    else if(jTBi.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Digite o nr de BI");
        jTBi.requestFocus();
        return false;
    }
     else if(jTnuitFunc.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Digite o nr de nuit");
        jTnuitFunc.requestFocus();
        return false;
    }
    
    if(jTdata.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Digite a data");
        jTdata.requestFocus();
        return false;
    }
    if(jTtelefoneFunc.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Digite o nr de telefone");
        jTtelefoneFunc.requestFocus();
        return false;
    }
    if(jTemailFunc.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Digite o email");
        jTemailFunc.requestFocus();
        return false;
    }
    
    if(jComboFuncao.getSelectedItem().equals("")){
        JOptionPane.showMessageDialog(null, "Digite a função");
        jComboFuncao.requestFocus();
        return false;
    }
        return true;
    }

}