/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
/**
 *
 * @author EGV
 */
import BaseDados.JavaConexao;
import Interface.Relatorio;
public class TelaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    JavaConexao jc = new JavaConexao();
    public TelaAdmin() {
        initComponents();
        setSize(700, 550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnAdmCad = new javax.swing.JButton();
        btnAdmApagar = new javax.swing.JButton();
        btnAdmActual = new javax.swing.JButton();
        btnAdmRelt = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBpesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 152, 152));
        jPanel6.setPreferredSize(new java.awt.Dimension(570, 10));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btnAdmCad.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmCad.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnAdmCad.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastro.png"))); // NOI18N
        btnAdmCad.setToolTipText("Cadastrar");
        btnAdmCad.setBorder(null);
        btnAdmCad.setBorderPainted(false);
        btnAdmCad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmCadActionPerformed(evt);
            }
        });

        btnAdmApagar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnAdmApagar.setText("Apagar");
        btnAdmApagar.setToolTipText("Apagar");
        btnAdmApagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAdmActual.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmActual.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnAdmActual.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/update.png"))); // NOI18N
        btnAdmActual.setToolTipText("Actualizar");
        btnAdmActual.setBorder(null);
        btnAdmActual.setBorderPainted(false);
        btnAdmActual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmActualActionPerformed(evt);
            }
        });

        btnAdmRelt.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmRelt.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnAdmRelt.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmRelt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/file (5).png"))); // NOI18N
        btnAdmRelt.setToolTipText("Ver relatório");
        btnAdmRelt.setBorder(null);
        btnAdmRelt.setBorderPainted(false);
        btnAdmRelt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmRelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmReltActionPerformed(evt);
            }
        });

        jBsair.setBackground(new java.awt.Color(255, 255, 255));
        jBsair.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jBsair.setForeground(new java.awt.Color(255, 255, 255));
        jBsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/previous.png"))); // NOI18N
        jBsair.setToolTipText("Sair");
        jBsair.setBorder(null);
        jBsair.setBorderPainted(false);
        jBsair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/worker (3).png"))); // NOI18N
        jButton2.setToolTipText("Administrador");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBpesquisa.setBackground(new java.awt.Color(255, 255, 255));
        jBpesquisa.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jBpesquisa.setForeground(new java.awt.Color(255, 255, 255));
        jBpesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jBpesquisa.setToolTipText("Pesquisar");
        jBpesquisa.setBorder(null);
        jBpesquisa.setBorderPainted(false);
        jBpesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdmCad, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jBsair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdmActual, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdmApagar))
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdmRelt, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jBpesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdmApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdmCad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdmActual, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBsair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(btnAdmRelt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(716, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmReltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmReltActionPerformed
        this.dispose();
        Relatorio rl = new Relatorio();
        rl.setLocationRelativeTo(null);
        rl.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAdmReltActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAdmActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmActualActionPerformed
        
        
    }//GEN-LAST:event_btnAdmActualActionPerformed

    private void btnAdmCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmCadActionPerformed
        this.dispose();
        FuncionarioCadastro fc = new FuncionarioCadastro();
        fc.setVisible(true);
        
        
            
    }//GEN-LAST:event_btnAdmCadActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
       this.dispose();
        LoginAdmin back = new LoginAdmin();
        back.setVisible(true);
    }//GEN-LAST:event_jBsairActionPerformed

    private void jBpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisaActionPerformed
        FuncionarioCadastro fcad = new FuncionarioCadastro();
        fcad.setVisible(true);
              
        
    }//GEN-LAST:event_jBpesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdmin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmActual;
    private javax.swing.JButton btnAdmApagar;
    private javax.swing.JButton btnAdmCad;
    private javax.swing.JButton btnAdmRelt;
    private javax.swing.JButton jBpesquisa;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
